### PR TITLE
Consider adding SSL support

### PR DESCRIPTION
**Pull request by bbqsrc**
Hey there,

I've added SSL support, and it is a very minor change, so I think it would be beneficial if you merge this into the upstream :)

Thanks.

### CODE REVIEW

**Comment by jthingelstad** [comment]
Thanks for providing this, I just put this in my copy of Phenny. Would really be nice if this was in the main release.

**Comment by bbqsrc** [comment]
Considering how simple the change is, yes, it would be. Does it still apply cleanly to mainline?

**Comment by jthingelstad** [comment]
I downloaded a fresh copy of the tar.bz yesterday and applied these changes to get it to connect to our SSL only server. Worked fine!

**Comment by ghost** [comment]
Thank you bbqsrc! Works great.

**Comment by sbp** [comment]
Would you mind squashing the commits so that I can pull it? Thanks!

**Comment by myano** [comment]
I did a git clone on bbqsrc's phenny repository and used the following in the default.py:

```
host = 'irc.freenode.net'
port = 7000
ssl = True
```

and phenny disconnects with:

```
Connecting to irc.freenode.net:7000... connected!
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...
```

**Comment by deed02392** [comment]
I'm afraid this doesn't work for me either. Same error as above.

**Pull request closed without merging**
